CREATE TABLE TS10_01.STUDENTS1
(
STUDENT_ID NUMBER(5) NOT NULL,
STUDENT_NAME VARCHAR2(20),
GROUP_ID FLOAT(5),
GROUP_ID1 BINARY_FLOAT,
GROUP_ID2 BINARY_DOUBLE
);

CREATE TABLE TS10_01.STUDENTS2
(
STUDENT_ID NUMBER(5) NOT NULL,
STUDENT_NAME VARCHAR2(20),
GROUP_ID FLOAT(5),
GROUP_ID1 BINARY_FLOAT,
GROUP_ID2 BINARY_DOUBLE
);

CREATE OR REPLACE PROCEDURE TS10_01.CREATE_TAB_STU2_TS10 
IS
BEGIN

MERGE INTO TS10_01.STUDENTS1 A
USING
(SELECT STUDENT_ID, STUDENT_NAME, GROUP_ID
FROM TS10_01.STUDENTS2) B
ON (A.STUDENT_ID = B.STUDENT_ID)
WHEN MATCHED THEN
UPDATE SET A.STUDENT_NAME = B.STUDENT_NAME
, A.GROUP_ID = B.GROUP_ID
WHEN NOT MATCHED THEN
INSERT (A.STUDENT_ID, A.STUDENT_NAME, A.GROUP_ID)
VALUES (B.STUDENT_ID, B.STUDENT_NAME, B.GROUP_ID);

END;
/